import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :ai_wisdom, AiWisdomWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

config :phoenix, :long_poll_timeout, 45_000

config :ai_wisdom, :deepseek,
  api_key: System.get_env("DEEPSEEK_API_KEY")

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
