import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :ai_wisdom, AiWisdomWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

config :ai_wisdom, AiWisdomWeb.Endpoint,
  url: [host: "ai-wisdom.onrender.com", port: 443],
  http: [
    port: String.to_integer(System.get_env("PORT") || "4001"),
    transport_options: [socket_opts: [:inet6]]
  ],
  check_origin: ["//ai-wisdom.onrender.com", "//*.render.com"]
# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
